export interface FlagData {
  country: string
  countryFr: string
  code: string
}

export const FLAGS: FlagData[] = [
  { country: 'Afghanistan', countryFr: 'Afghanistan', code: 'af' },
  { country: 'Albania', countryFr: 'Albanie', code: 'al' },
  { country: 'Algeria', countryFr: 'Algérie', code: 'dz' },
  { country: 'Andorra', countryFr: 'Andorre', code: 'ad' },
  { country: 'Angola', countryFr: 'Angola', code: 'ao' },
  { country: 'Antigua and Barbuda', countryFr: 'Antigua-et-Barbuda', code: 'ag' },
  { country: 'Argentina', countryFr: 'Argentine', code: 'ar' },
  { country: 'Armenia', countryFr: 'Arménie', code: 'am' },
  { country: 'Australia', countryFr: 'Australie', code: 'au' },
  { country: 'Austria', countryFr: 'Autriche', code: 'at' },
  { country: 'Azerbaijan', countryFr: 'Azerbaïdjan', code: 'az' },
  { country: 'Bahamas', countryFr: 'Bahamas', code: 'bs' },
  { country: 'Bahrain', countryFr: 'Bahreïn', code: 'bh' },
  { country: 'Bangladesh', countryFr: 'Bangladesh', code: 'bd' },
  { country: 'Barbados', countryFr: 'Barbade', code: 'bb' },
  { country: 'Belarus', countryFr: 'Biélorussie', code: 'by' },
  { country: 'Belgium', countryFr: 'Belgique', code: 'be' },
  { country: 'Belize', countryFr: 'Belize', code: 'bz' },
  { country: 'Benin', countryFr: 'Bénin', code: 'bj' },
  { country: 'Bhutan', countryFr: 'Bhoutan', code: 'bt' },
  { country: 'Bolivia', countryFr: 'Bolivie', code: 'bo' },
  { country: 'Bosnia and Herzegovina', countryFr: 'Bosnie-Herzégovine', code: 'ba' },
  { country: 'Botswana', countryFr: 'Botswana', code: 'bw' },
  { country: 'Brazil', countryFr: 'Brésil', code: 'br' },
  { country: 'Brunei', countryFr: 'Brunei', code: 'bn' },
  { country: 'Bulgaria', countryFr: 'Bulgarie', code: 'bg' },
  { country: 'Burkina Faso', countryFr: 'Burkina Faso', code: 'bf' },
  { country: 'Burundi', countryFr: 'Burundi', code: 'bi' },
  { country: 'Cambodia', countryFr: 'Cambodge', code: 'kh' },
  { country: 'Cameroon', countryFr: 'Cameroun', code: 'cm' },
  { country: 'Canada', countryFr: 'Canada', code: 'ca' },
  { country: 'Cape Verde', countryFr: 'Cap-Vert', code: 'cv' },
  { country: 'Central African Republic', countryFr: 'République centrafricaine', code: 'cf' },
  { country: 'Chad', countryFr: 'Tchad', code: 'td' },
  { country: 'Chile', countryFr: 'Chili', code: 'cl' },
  { country: 'China', countryFr: 'Chine', code: 'cn' },
  { country: 'Colombia', countryFr: 'Colombie', code: 'co' },
  { country: 'Comoros', countryFr: 'Comores', code: 'km' },
  { country: 'Congo', countryFr: 'Congo', code: 'cg' },
  { country: 'Costa Rica', countryFr: 'Costa Rica', code: 'cr' },
  { country: 'Croatia', countryFr: 'Croatie', code: 'hr' },
  { country: 'Cuba', countryFr: 'Cuba', code: 'cu' },
  { country: 'Cyprus', countryFr: 'Chypre', code: 'cy' },
  { country: 'Czech Republic', countryFr: 'République tchèque', code: 'cz' },
  { country: 'Democratic Republic of the Congo', countryFr: 'République démocratique du Congo', code: 'cd' },
  { country: 'Denmark', countryFr: 'Danemark', code: 'dk' },
  { country: 'Djibouti', countryFr: 'Djibouti', code: 'dj' },
  { country: 'Dominica', countryFr: 'Dominique', code: 'dm' },
  { country: 'Dominican Republic', countryFr: 'République dominicaine', code: 'do' },
  { country: 'East Timor', countryFr: 'Timor oriental', code: 'tl' },
  { country: 'Ecuador', countryFr: 'Équateur', code: 'ec' },
  { country: 'Egypt', countryFr: 'Égypte', code: 'eg' },
  { country: 'El Salvador', countryFr: 'Salvador', code: 'sv' },
  { country: 'Equatorial Guinea', countryFr: 'Guinée équatoriale', code: 'gq' },
  { country: 'Eritrea', countryFr: 'Érythrée', code: 'er' },
  { country: 'Estonia', countryFr: 'Estonie', code: 'ee' },
  { country: 'Eswatini', countryFr: 'Eswatini', code: 'sz' },
  { country: 'Ethiopia', countryFr: 'Éthiopie', code: 'et' },
  { country: 'Fiji', countryFr: 'Fidji', code: 'fj' },
  { country: 'Finland', countryFr: 'Finlande', code: 'fi' },
  { country: 'France', countryFr: 'France', code: 'fr' },
  { country: 'Gabon', countryFr: 'Gabon', code: 'ga' },
  { country: 'Gambia', countryFr: 'Gambie', code: 'gm' },
  { country: 'Georgia', countryFr: 'Géorgie', code: 'ge' },
  { country: 'Germany', countryFr: 'Allemagne', code: 'de' },
  { country: 'Ghana', countryFr: 'Ghana', code: 'gh' },
  { country: 'Greece', countryFr: 'Grèce', code: 'gr' },
  { country: 'Grenada', countryFr: 'Grenade', code: 'gd' },
  { country: 'Guatemala', countryFr: 'Guatemala', code: 'gt' },
  { country: 'Guinea', countryFr: 'Guinée', code: 'gn' },
  { country: 'Guinea-Bissau', countryFr: 'Guinée-Bissau', code: 'gw' },
  { country: 'Guyana', countryFr: 'Guyana', code: 'gy' },
  { country: 'Haiti', countryFr: 'Haïti', code: 'ht' },
  { country: 'Honduras', countryFr: 'Honduras', code: 'hn' },
  { country: 'Hungary', countryFr: 'Hongrie', code: 'hu' },
  { country: 'Iceland', countryFr: 'Islande', code: 'is' },
  { country: 'India', countryFr: 'Inde', code: 'in' },
  { country: 'Indonesia', countryFr: 'Indonésie', code: 'id' },
  { country: 'Iran', countryFr: 'Iran', code: 'ir' },
  { country: 'Iraq', countryFr: 'Irak', code: 'iq' },
  { country: 'Ireland', countryFr: 'Irlande', code: 'ie' },
  { country: 'Israel', countryFr: 'Israël', code: 'il' },
  { country: 'Italy', countryFr: 'Italie', code: 'it' },
  { country: 'Ivory Coast', countryFr: 'Côte d\'Ivoire', code: 'ci' },
  { country: 'Jamaica', countryFr: 'Jamaïque', code: 'jm' },
  { country: 'Japan', countryFr: 'Japon', code: 'jp' },
  { country: 'Jordan', countryFr: 'Jordanie', code: 'jo' },
  { country: 'Kazakhstan', countryFr: 'Kazakhstan', code: 'kz' },
  { country: 'Kenya', countryFr: 'Kenya', code: 'ke' },
  { country: 'Kiribati', countryFr: 'Kiribati', code: 'ki' },
  { country: 'Kuwait', countryFr: 'Koweït', code: 'kw' },
  { country: 'Kyrgyzstan', countryFr: 'Kirghizistan', code: 'kg' },
  { country: 'Laos', countryFr: 'Laos', code: 'la' },
  { country: 'Latvia', countryFr: 'Lettonie', code: 'lv' },
  { country: 'Lebanon', countryFr: 'Liban', code: 'lb' },
  { country: 'Lesotho', countryFr: 'Lesotho', code: 'ls' },
  { country: 'Liberia', countryFr: 'Libéria', code: 'lr' },
  { country: 'Libya', countryFr: 'Libye', code: 'ly' },
  { country: 'Liechtenstein', countryFr: 'Liechtenstein', code: 'li' },
  { country: 'Lithuania', countryFr: 'Lituanie', code: 'lt' },
  { country: 'Luxembourg', countryFr: 'Luxembourg', code: 'lu' },
  { country: 'Madagascar', countryFr: 'Madagascar', code: 'mg' },
  { country: 'Malawi', countryFr: 'Malawi', code: 'mw' },
  { country: 'Malaysia', countryFr: 'Malaisie', code: 'my' },
  { country: 'Maldives', countryFr: 'Maldives', code: 'mv' },
  { country: 'Mali', countryFr: 'Mali', code: 'ml' },
  { country: 'Malta', countryFr: 'Malte', code: 'mt' },
  { country: 'Marshall Islands', countryFr: 'Îles Marshall', code: 'mh' },
  { country: 'Mauritania', countryFr: 'Mauritanie', code: 'mr' },
  { country: 'Mauritius', countryFr: 'Maurice', code: 'mu' },
  { country: 'Mexico', countryFr: 'Mexique', code: 'mx' },
  { country: 'Micronesia', countryFr: 'Micronésie', code: 'fm' },
  { country: 'Moldova', countryFr: 'Moldavie', code: 'md' },
  { country: 'Monaco', countryFr: 'Monaco', code: 'mc' },
  { country: 'Mongolia', countryFr: 'Mongolie', code: 'mn' },
  { country: 'Montenegro', countryFr: 'Monténégro', code: 'me' },
  { country: 'Morocco', countryFr: 'Maroc', code: 'ma' },
  { country: 'Mozambique', countryFr: 'Mozambique', code: 'mz' },
  { country: 'Myanmar', countryFr: 'Myanmar', code: 'mm' },
  { country: 'Namibia', countryFr: 'Namibie', code: 'na' },
  { country: 'Nauru', countryFr: 'Nauru', code: 'nr' },
  { country: 'Nepal', countryFr: 'Népal', code: 'np' },
  { country: 'Netherlands', countryFr: 'Pays-Bas', code: 'nl' },
  { country: 'New Zealand', countryFr: 'Nouvelle-Zélande', code: 'nz' },
  { country: 'Nicaragua', countryFr: 'Nicaragua', code: 'ni' },
  { country: 'Niger', countryFr: 'Niger', code: 'ne' },
  { country: 'Nigeria', countryFr: 'Nigéria', code: 'ng' },
  { country: 'North Korea', countryFr: 'Corée du Nord', code: 'kp' },
  { country: 'North Macedonia', countryFr: 'Macédoine du Nord', code: 'mk' },
  { country: 'Norway', countryFr: 'Norvège', code: 'no' },
  { country: 'Oman', countryFr: 'Oman', code: 'om' },
  { country: 'Pakistan', countryFr: 'Pakistan', code: 'pk' },
  { country: 'Palau', countryFr: 'Palaos', code: 'pw' },
  { country: 'Palestine', countryFr: 'Palestine', code: 'ps' },
  { country: 'Panama', countryFr: 'Panama', code: 'pa' },
  { country: 'Papua New Guinea', countryFr: 'Papouasie-Nouvelle-Guinée', code: 'pg' },
  { country: 'Paraguay', countryFr: 'Paraguay', code: 'py' },
  { country: 'Peru', countryFr: 'Pérou', code: 'pe' },
  { country: 'Philippines', countryFr: 'Philippines', code: 'ph' },
  { country: 'Poland', countryFr: 'Pologne', code: 'pl' },
  { country: 'Portugal', countryFr: 'Portugal', code: 'pt' },
  { country: 'Qatar', countryFr: 'Qatar', code: 'qa' },
  { country: 'Romania', countryFr: 'Roumanie', code: 'ro' },
  { country: 'Russia', countryFr: 'Russie', code: 'ru' },
  { country: 'Rwanda', countryFr: 'Rwanda', code: 'rw' },
  { country: 'Saint Kitts and Nevis', countryFr: 'Saint-Christophe-et-Niévès', code: 'kn' },
  { country: 'Saint Lucia', countryFr: 'Sainte-Lucie', code: 'lc' },
  { country: 'Saint Vincent and the Grenadines', countryFr: 'Saint-Vincent-et-les-Grenadines', code: 'vc' },
  { country: 'Samoa', countryFr: 'Samoa', code: 'ws' },
  { country: 'San Marino', countryFr: 'Saint-Marin', code: 'sm' },
  { country: 'Sao Tome and Principe', countryFr: 'Sao Tomé-et-Principe', code: 'st' },
  { country: 'Saudi Arabia', countryFr: 'Arabie saoudite', code: 'sa' },
  { country: 'Senegal', countryFr: 'Sénégal', code: 'sn' },
  { country: 'Serbia', countryFr: 'Serbie', code: 'rs' },
  { country: 'Seychelles', countryFr: 'Seychelles', code: 'sc' },
  { country: 'Sierra Leone', countryFr: 'Sierra Leone', code: 'sl' },
  { country: 'Singapore', countryFr: 'Singapour', code: 'sg' },
  { country: 'Slovakia', countryFr: 'Slovaquie', code: 'sk' },
  { country: 'Slovenia', countryFr: 'Slovénie', code: 'si' },
  { country: 'Solomon Islands', countryFr: 'Îles Salomon', code: 'sb' },
  { country: 'Somalia', countryFr: 'Somalie', code: 'so' },
  { country: 'South Africa', countryFr: 'Afrique du Sud', code: 'za' },
  { country: 'South Korea', countryFr: 'Corée du Sud', code: 'kr' },
  { country: 'South Sudan', countryFr: 'Soudan du Sud', code: 'ss' },
  { country: 'Spain', countryFr: 'Espagne', code: 'es' },
  { country: 'Sri Lanka', countryFr: 'Sri Lanka', code: 'lk' },
  { country: 'Sudan', countryFr: 'Soudan', code: 'sd' },
  { country: 'Suriname', countryFr: 'Suriname', code: 'sr' },
  { country: 'Sweden', countryFr: 'Suède', code: 'se' },
  { country: 'Switzerland', countryFr: 'Suisse', code: 'ch' },
  { country: 'Syria', countryFr: 'Syrie', code: 'sy' },
  { country: 'Taiwan', countryFr: 'Taïwan', code: 'tw' },
  { country: 'Tajikistan', countryFr: 'Tadjikistan', code: 'tj' },
  { country: 'Tanzania', countryFr: 'Tanzanie', code: 'tz' },
  { country: 'Thailand', countryFr: 'Thaïlande', code: 'th' },
  { country: 'Togo', countryFr: 'Togo', code: 'tg' },
  { country: 'Tonga', countryFr: 'Tonga', code: 'to' },
  { country: 'Trinidad and Tobago', countryFr: 'Trinité-et-Tobago', code: 'tt' },
  { country: 'Tunisia', countryFr: 'Tunisie', code: 'tn' },
  { country: 'Turkey', countryFr: 'Turquie', code: 'tr' },
  { country: 'Turkmenistan', countryFr: 'Turkménistan', code: 'tm' },
  { country: 'Tuvalu', countryFr: 'Tuvalu', code: 'tv' },
  { country: 'Uganda', countryFr: 'Ouganda', code: 'ug' },
  { country: 'Ukraine', countryFr: 'Ukraine', code: 'ua' },
  { country: 'United Arab Emirates', countryFr: 'Émirats arabes unis', code: 'ae' },
  { country: 'United Kingdom', countryFr: 'Royaume-Uni', code: 'gb' },
  { country: 'United States', countryFr: 'États-Unis', code: 'us' },
  { country: 'Uruguay', countryFr: 'Uruguay', code: 'uy' },
  { country: 'Uzbekistan', countryFr: 'Ouzbékistan', code: 'uz' },
  { country: 'Vanuatu', countryFr: 'Vanuatu', code: 'vu' },
  { country: 'Vatican City', countryFr: 'Vatican', code: 'va' },
  { country: 'Venezuela', countryFr: 'Venezuela', code: 've' },
  { country: 'Vietnam', countryFr: 'Vietnam', code: 'vn' },
  { country: 'Yemen', countryFr: 'Yémen', code: 'ye' },
  { country: 'Zambia', countryFr: 'Zambie', code: 'zm' },
  { country: 'Zimbabwe', countryFr: 'Zimbabwe', code: 'zw' }
]