export interface FlagData {
  country: string
  countryFr: string
  flag: string
}

export const FLAGS: FlagData[] = [
  { country: 'Afghanistan', countryFr: 'Afghanistan', flag: '🇦🇫' },
  { country: 'Albania', countryFr: 'Albanie', flag: '🇦🇱' },
  { country: 'Algeria', countryFr: 'Algérie', flag: '🇩🇿' },
  { country: 'Andorra', countryFr: 'Andorre', flag: '🇦🇩' },
  { country: 'Angola', countryFr: 'Angola', flag: '🇦🇴' },
  { country: 'Antigua and Barbuda', countryFr: 'Antigua-et-Barbuda', flag: '🇦🇬' },
  { country: 'Argentina', countryFr: 'Argentine', flag: '🇦🇷' },
  { country: 'Armenia', countryFr: 'Arménie', flag: '🇦🇲' },
  { country: 'Australia', countryFr: 'Australie', flag: '🇦🇺' },
  { country: 'Austria', countryFr: 'Autriche', flag: '🇦🇹' },
  { country: 'Azerbaijan', countryFr: 'Azerbaïdjan', flag: '🇦🇿' },
  { country: 'Bahamas', countryFr: 'Bahamas', flag: '🇧🇸' },
  { country: 'Bahrain', countryFr: 'Bahreïn', flag: '🇧🇭' },
  { country: 'Bangladesh', countryFr: 'Bangladesh', flag: '🇧🇩' },
  { country: 'Barbados', countryFr: 'Barbade', flag: '🇧🇧' },
  { country: 'Belarus', countryFr: 'Biélorussie', flag: '🇧🇾' },
  { country: 'Belgium', countryFr: 'Belgique', flag: '🇧🇪' },
  { country: 'Belize', countryFr: 'Belize', flag: '🇧🇿' },
  { country: 'Benin', countryFr: 'Bénin', flag: '🇧🇯' },
  { country: 'Bhutan', countryFr: 'Bhoutan', flag: '🇧🇹' },
  { country: 'Bolivia', countryFr: 'Bolivie', flag: '🇧🇴' },
  { country: 'Bosnia and Herzegovina', countryFr: 'Bosnie-Herzégovine', flag: '🇧🇦' },
  { country: 'Botswana', countryFr: 'Botswana', flag: '🇧🇼' },
  { country: 'Brazil', countryFr: 'Brésil', flag: '🇧🇷' },
  { country: 'Brunei', countryFr: 'Brunei', flag: '🇧🇳' },
  { country: 'Bulgaria', countryFr: 'Bulgarie', flag: '🇧🇬' },
  { country: 'Burkina Faso', countryFr: 'Burkina Faso', flag: '🇧🇫' },
  { country: 'Burundi', countryFr: 'Burundi', flag: '🇧🇮' },
  { country: 'Cambodia', countryFr: 'Cambodge', flag: '🇰🇭' },
  { country: 'Cameroon', countryFr: 'Cameroun', flag: '🇨🇲' },
  { country: 'Canada', countryFr: 'Canada', flag: '🇨🇦' },
  { country: 'Cape Verde', countryFr: 'Cap-Vert', flag: '🇨🇻' },
  { country: 'Central African Republic', countryFr: 'République centrafricaine', flag: '🇨🇫' },
  { country: 'Chad', countryFr: 'Tchad', flag: '🇹🇩' },
  { country: 'Chile', countryFr: 'Chili', flag: '🇨🇱' },
  { country: 'China', countryFr: 'Chine', flag: '🇨🇳' },
  { country: 'Colombia', countryFr: 'Colombie', flag: '🇨🇴' },
  { country: 'Comoros', countryFr: 'Comores', flag: '🇰🇲' },
  { country: 'Congo', countryFr: 'Congo', flag: '🇨🇬' },
  { country: 'Costa Rica', countryFr: 'Costa Rica', flag: '🇨🇷' },
  { country: 'Croatia', countryFr: 'Croatie', flag: '🇭🇷' },
  { country: 'Cuba', countryFr: 'Cuba', flag: '🇨🇺' },
  { country: 'Cyprus', countryFr: 'Chypre', flag: '🇨🇾' },
  { country: 'Czech Republic', countryFr: 'République tchèque', flag: '🇨🇿' },
  { country: 'Democratic Republic of the Congo', countryFr: 'République démocratique du Congo', flag: '🇨🇩' },
  { country: 'Denmark', countryFr: 'Danemark', flag: '🇩🇰' },
  { country: 'Djibouti', countryFr: 'Djibouti', flag: '🇩🇯' },
  { country: 'Dominica', countryFr: 'Dominique', flag: '🇩🇲' },
  { country: 'Dominican Republic', countryFr: 'République dominicaine', flag: '🇩🇴' },
  { country: 'East Timor', countryFr: 'Timor oriental', flag: '🇹🇱' },
  { country: 'Ecuador', countryFr: 'Équateur', flag: '🇪🇨' },
  { country: 'Egypt', countryFr: 'Égypte', flag: '🇪🇬' },
  { country: 'El Salvador', countryFr: 'Salvador', flag: '🇸🇻' },
  { country: 'Equatorial Guinea', countryFr: 'Guinée équatoriale', flag: '🇬🇶' },
  { country: 'Eritrea', countryFr: 'Érythrée', flag: '🇪🇷' },
  { country: 'Estonia', countryFr: 'Estonie', flag: '🇪🇪' },
  { country: 'Eswatini', countryFr: 'Eswatini', flag: '🇸🇿' },
  { country: 'Ethiopia', countryFr: 'Éthiopie', flag: '🇪🇹' },
  { country: 'Fiji', countryFr: 'Fidji', flag: '🇫🇯' },
  { country: 'Finland', countryFr: 'Finlande', flag: '🇫🇮' },
  { country: 'France', countryFr: 'France', flag: '🇫🇷' },
  { country: 'Gabon', countryFr: 'Gabon', flag: '🇬🇦' },
  { country: 'Gambia', countryFr: 'Gambie', flag: '🇬🇲' },
  { country: 'Georgia', countryFr: 'Géorgie', flag: '🇬🇪' },
  { country: 'Germany', countryFr: 'Allemagne', flag: '🇩🇪' },
  { country: 'Ghana', countryFr: 'Ghana', flag: '🇬🇭' },
  { country: 'Greece', countryFr: 'Grèce', flag: '🇬🇷' },
  { country: 'Grenada', countryFr: 'Grenade', flag: '🇬🇩' },
  { country: 'Guatemala', countryFr: 'Guatemala', flag: '🇬🇹' },
  { country: 'Guinea', countryFr: 'Guinée', flag: '🇬🇳' },
  { country: 'Guinea-Bissau', countryFr: 'Guinée-Bissau', flag: '🇬🇼' },
  { country: 'Guyana', countryFr: 'Guyana', flag: '🇬🇾' },
  { country: 'Haiti', countryFr: 'Haïti', flag: '🇭🇹' },
  { country: 'Honduras', countryFr: 'Honduras', flag: '🇭🇳' },
  { country: 'Hungary', countryFr: 'Hongrie', flag: '🇭🇺' },
  { country: 'Iceland', countryFr: 'Islande', flag: '🇮🇸' },
  { country: 'India', countryFr: 'Inde', flag: '🇮🇳' },
  { country: 'Indonesia', countryFr: 'Indonésie', flag: '🇮🇩' },
  { country: 'Iran', countryFr: 'Iran', flag: '🇮🇷' },
  { country: 'Iraq', countryFr: 'Irak', flag: '🇮🇶' },
  { country: 'Ireland', countryFr: 'Irlande', flag: '🇮🇪' },
  { country: 'Israel', countryFr: 'Israël', flag: '🇮🇱' },
  { country: 'Italy', countryFr: 'Italie', flag: '🇮🇹' },
  { country: 'Ivory Coast', countryFr: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { country: 'Jamaica', countryFr: 'Jamaïque', flag: '🇯🇲' },
  { country: 'Japan', countryFr: 'Japon', flag: '🇯🇵' },
  { country: 'Jordan', countryFr: 'Jordanie', flag: '🇯🇴' },
  { country: 'Kazakhstan', countryFr: 'Kazakhstan', flag: '🇰🇿' },
  { country: 'Kenya', countryFr: 'Kenya', flag: '🇰🇪' },
  { country: 'Kiribati', countryFr: 'Kiribati', flag: '🇰🇮' },
  { country: 'Kuwait', countryFr: 'Koweït', flag: '🇰🇼' },
  { country: 'Kyrgyzstan', countryFr: 'Kirghizistan', flag: '🇰🇬' },
  { country: 'Laos', countryFr: 'Laos', flag: '🇱🇦' },
  { country: 'Latvia', countryFr: 'Lettonie', flag: '🇱🇻' },
  { country: 'Lebanon', countryFr: 'Liban', flag: '🇱🇧' },
  { country: 'Lesotho', countryFr: 'Lesotho', flag: '🇱🇸' },
  { country: 'Liberia', countryFr: 'Libéria', flag: '🇱🇷' },
  { country: 'Libya', countryFr: 'Libye', flag: '🇱🇾' },
  { country: 'Liechtenstein', countryFr: 'Liechtenstein', flag: '🇱🇮' },
  { country: 'Lithuania', countryFr: 'Lituanie', flag: '🇱🇹' },
  { country: 'Luxembourg', countryFr: 'Luxembourg', flag: '🇱🇺' },
  { country: 'Madagascar', countryFr: 'Madagascar', flag: '🇲🇬' },
  { country: 'Malawi', countryFr: 'Malawi', flag: '🇲🇼' },
  { country: 'Malaysia', countryFr: 'Malaisie', flag: '🇲🇾' },
  { country: 'Maldives', countryFr: 'Maldives', flag: '🇲🇻' },
  { country: 'Mali', countryFr: 'Mali', flag: '🇲🇱' },
  { country: 'Malta', countryFr: 'Malte', flag: '🇲🇹' },
  { country: 'Marshall Islands', countryFr: 'Îles Marshall', flag: '🇲🇭' },
  { country: 'Mauritania', countryFr: 'Mauritanie', flag: '🇲🇷' },
  { country: 'Mauritius', countryFr: 'Maurice', flag: '🇲🇺' },
  { country: 'Mexico', countryFr: 'Mexique', flag: '🇲🇽' },
  { country: 'Micronesia', countryFr: 'Micronésie', flag: '🇫🇲' },
  { country: 'Moldova', countryFr: 'Moldavie', flag: '🇲🇩' },
  { country: 'Monaco', countryFr: 'Monaco', flag: '🇲🇨' },
  { country: 'Mongolia', countryFr: 'Mongolie', flag: '🇲🇳' },
  { country: 'Montenegro', countryFr: 'Monténégro', flag: '🇲🇪' },
  { country: 'Morocco', countryFr: 'Maroc', flag: '🇲🇦' },
  { country: 'Mozambique', countryFr: 'Mozambique', flag: '🇲🇿' },
  { country: 'Myanmar', countryFr: 'Myanmar', flag: '🇲🇲' },
  { country: 'Namibia', countryFr: 'Namibie', flag: '🇳🇦' },
  { country: 'Nauru', countryFr: 'Nauru', flag: '🇳🇷' },
  { country: 'Nepal', countryFr: 'Népal', flag: '🇳🇵' },
  { country: 'Netherlands', countryFr: 'Pays-Bas', flag: '🇳🇱' },
  { country: 'New Zealand', countryFr: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { country: 'Nicaragua', countryFr: 'Nicaragua', flag: '🇳🇮' },
  { country: 'Niger', countryFr: 'Niger', flag: '🇳🇪' },
  { country: 'Nigeria', countryFr: 'Nigéria', flag: '🇳🇬' },
  { country: 'North Korea', countryFr: 'Corée du Nord', flag: '🇰🇵' },
  { country: 'North Macedonia', countryFr: 'Macédoine du Nord', flag: '🇲🇰' },
  { country: 'Norway', countryFr: 'Norvège', flag: '🇳🇴' },
  { country: 'Oman', countryFr: 'Oman', flag: '🇴🇲' },
  { country: 'Pakistan', countryFr: 'Pakistan', flag: '🇵🇰' },
  { country: 'Palau', countryFr: 'Palaos', flag: '🇵🇼' },
  { country: 'Palestine', countryFr: 'Palestine', flag: '🇵🇸' },
  { country: 'Panama', countryFr: 'Panama', flag: '🇵🇦' },
  { country: 'Papua New Guinea', countryFr: 'Papouasie-Nouvelle-Guinée', flag: '🇵🇬' },
  { country: 'Paraguay', countryFr: 'Paraguay', flag: '🇵🇾' },
  { country: 'Peru', countryFr: 'Pérou', flag: '🇵🇪' },
  { country: 'Philippines', countryFr: 'Philippines', flag: '🇵🇭' },
  { country: 'Poland', countryFr: 'Pologne', flag: '🇵🇱' },
  { country: 'Portugal', countryFr: 'Portugal', flag: '🇵🇹' },
  { country: 'Qatar', countryFr: 'Qatar', flag: '🇶🇦' },
  { country: 'Romania', countryFr: 'Roumanie', flag: '🇷🇴' },
  { country: 'Russia', countryFr: 'Russie', flag: '🇷🇺' },
  { country: 'Rwanda', countryFr: 'Rwanda', flag: '🇷🇼' },
  { country: 'Saint Kitts and Nevis', countryFr: 'Saint-Christophe-et-Niévès', flag: '🇰🇳' },
  { country: 'Saint Lucia', countryFr: 'Sainte-Lucie', flag: '🇱🇨' },
  { country: 'Saint Vincent and the Grenadines', countryFr: 'Saint-Vincent-et-les-Grenadines', flag: '🇻🇨' },
  { country: 'Samoa', countryFr: 'Samoa', flag: '🇼🇸' },
  { country: 'San Marino', countryFr: 'Saint-Marin', flag: '🇸🇲' },
  { country: 'Sao Tome and Principe', countryFr: 'Sao Tomé-et-Principe', flag: '🇸🇹' },
  { country: 'Saudi Arabia', countryFr: 'Arabie saoudite', flag: '🇸🇦' },
  { country: 'Senegal', countryFr: 'Sénégal', flag: '🇸🇳' },
  { country: 'Serbia', countryFr: 'Serbie', flag: '🇷🇸' },
  { country: 'Seychelles', countryFr: 'Seychelles', flag: '🇸🇨' },
  { country: 'Sierra Leone', countryFr: 'Sierra Leone', flag: '🇸🇱' },
  { country: 'Singapore', countryFr: 'Singapour', flag: '🇸🇬' },
  { country: 'Slovakia', countryFr: 'Slovaquie', flag: '🇸🇰' },
  { country: 'Slovenia', countryFr: 'Slovénie', flag: '🇸🇮' },
  { country: 'Solomon Islands', countryFr: 'Îles Salomon', flag: '🇸🇧' },
  { country: 'Somalia', countryFr: 'Somalie', flag: '🇸🇴' },
  { country: 'South Africa', countryFr: 'Afrique du Sud', flag: '🇿🇦' },
  { country: 'South Korea', countryFr: 'Corée du Sud', flag: '🇰🇷' },
  { country: 'South Sudan', countryFr: 'Soudan du Sud', flag: '🇸🇸' },
  { country: 'Spain', countryFr: 'Espagne', flag: '🇪🇸' },
  { country: 'Sri Lanka', countryFr: 'Sri Lanka', flag: '🇱🇰' },
  { country: 'Sudan', countryFr: 'Soudan', flag: '🇸🇩' },
  { country: 'Suriname', countryFr: 'Suriname', flag: '🇸🇷' },
  { country: 'Sweden', countryFr: 'Suède', flag: '🇸🇪' },
  { country: 'Switzerland', countryFr: 'Suisse', flag: '🇨🇭' },
  { country: 'Syria', countryFr: 'Syrie', flag: '🇸🇾' },
  { country: 'Taiwan', countryFr: 'Taïwan', flag: '🇹🇼' },
  { country: 'Tajikistan', countryFr: 'Tadjikistan', flag: '🇹🇯' },
  { country: 'Tanzania', countryFr: 'Tanzanie', flag: '🇹🇿' },
  { country: 'Thailand', countryFr: 'Thaïlande', flag: '🇹🇭' },
  { country: 'Togo', countryFr: 'Togo', flag: '🇹🇬' },
  { country: 'Tonga', countryFr: 'Tonga', flag: '🇹🇴' },
  { country: 'Trinidad and Tobago', countryFr: 'Trinité-et-Tobago', flag: '🇹🇹' },
  { country: 'Tunisia', countryFr: 'Tunisie', flag: '🇹🇳' },
  { country: 'Turkey', countryFr: 'Turquie', flag: '🇹🇷' },
  { country: 'Turkmenistan', countryFr: 'Turkménistan', flag: '🇹🇲' },
  { country: 'Tuvalu', countryFr: 'Tuvalu', flag: '🇹🇻' },
  { country: 'Uganda', countryFr: 'Ouganda', flag: '🇺🇬' },
  { country: 'Ukraine', countryFr: 'Ukraine', flag: '🇺🇦' },
  { country: 'United Arab Emirates', countryFr: 'Émirats arabes unis', flag: '🇦🇪' },
  { country: 'United Kingdom', countryFr: 'Royaume-Uni', flag: '🇬🇧' },
  { country: 'United States', countryFr: 'États-Unis', flag: '🇺🇸' },
  { country: 'Uruguay', countryFr: 'Uruguay', flag: '🇺🇾' },
  { country: 'Uzbekistan', countryFr: 'Ouzbékistan', flag: '🇺🇿' },
  { country: 'Vanuatu', countryFr: 'Vanuatu', flag: '🇻🇺' },
  { country: 'Vatican City', countryFr: 'Vatican', flag: '🇻🇦' },
  { country: 'Venezuela', countryFr: 'Venezuela', flag: '🇻🇪' },
  { country: 'Vietnam', countryFr: 'Vietnam', flag: '🇻🇳' },
  { country: 'Yemen', countryFr: 'Yémen', flag: '🇾🇪' },
  { country: 'Zambia', countryFr: 'Zambie', flag: '🇿🇲' },
  { country: 'Zimbabwe', countryFr: 'Zimbabwe', flag: '🇿🇼' }
]